/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 model.glb 
Author: RalphDeving (https://sketchfab.com/RalphDeving)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/three-headed-geek-69c8d95b57564a4fabd589f589b6d63f
Title: Three Headed Geek
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  const group = useRef();
  const [rotationSpeed] = useState(0.01); // Velocidad de rotación
  useFrame(() => {
    group.current.rotation.z += rotationSpeed; // Girar alrededor del eje Y
  });

  return (
    <group {...props} dispose={null}>
      <group ref={group} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Gaben_1.geometry} material={materials.Gaben} />
        <mesh geometry={nodes.GabenLentes_1.geometry} material={materials.GabenLentes} />
        <mesh geometry={nodes.GabenVidrio_1.geometry} material={materials.GabenVidrio} />
        <mesh geometry={nodes.Gates_1.geometry} material={materials.Gates} />
        <mesh geometry={nodes.GatesLentes_1.geometry} material={materials.GatesLentes} />
        <mesh geometry={nodes.GatesVidrio_1.geometry} material={materials.GatesVidrio} />
        <mesh geometry={nodes.Body_1.geometry} material={materials.Body} />
        <mesh geometry={nodes.Jobs_1.geometry} material={materials.Jobs} />
        <mesh geometry={nodes.JobsLentes_1.geometry} material={materials.JobsLentes} />
        <mesh geometry={nodes.JobsVidrio_1.geometry} material={materials.JobsVidrio} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
